texts = {
    "English": {
        "title": "📱 Google Play Reviews Scraper",
        "enter_app_id": "Enter App ID",
        "num_comments": "Number of reviews to fetch",
        "fetch_comments": "Fetch Reviews",
        "fetching": "Fetching reviews…",
        "fetch_complete": "✅ Reviews fetching completed! ({count} reviews retrieved)",
        "excel_saved": "📂 Excel file saved!",
        "download_excel": "Download Excel File",
        "analyze_button": "Run Sentiment Analysis & Word Cloud",
        "analyzing": "Analyzing…",
        "analysis_complete": "✅ Analysis completed!",
        "sentiment_results": "Sentiment Analysis Results:",
        "no_positive": "No positive reviews, Word Cloud could not be generated.",
        "no_negative": "No negative reviews, Word Cloud could not be generated.",
        "positive_wc": "Positive Reviews Word Cloud",
        "negative_wc": "Negative Reviews Word Cloud",
        "progress": "Progress",
        "eta": "Estimated time left"
    },
    "Türkçe": {
        "title": "📱 Google Play Reviews Scraper",
        "enter_app_id": "Uygulama ID'si girin",
        "num_comments": "Kaç yorum çekilsin?",
        "fetch_comments": "Yorumları Çek",
        "fetching": "Yorumlar çekiliyor…",
        "fetch_complete": "✅ Yorum çekme tamamlandı! ({count} yorum alındı)",
        "excel_saved": "📂 Excel Dosyası Kaydedildi!",
        "download_excel": "Excel Dosyasını İndir",
        "analyze_button": "Duygu Analizi ve Word Cloud Oluştur",
        "analyzing": "Analiz yapılıyor…",
        "analysis_complete": "✅ Analiz tamamlandı!",
        "sentiment_results": "Duygu Analizi Sonuçları:",
        "no_positive": "Pozitif yorum yok, Word Cloud oluşturulamadı.",
        "no_negative": "Negatif yorum yok, Word Cloud oluşturulamadı.",
        "positive_wc": "Pozitif Yorum Word Cloud",
        "negative_wc": "Negatif Yorum Word Cloud",
        "progress": "İlerleme",
        "eta": "Tahmini kalan süre"
    },
    "Deutsch": {
        "title": "📱 Google Play Reviews Scraper",
        "enter_app_id": "App-ID eingeben",
        "num_comments": "Anzahl der Rezensionen zum Abrufen",
        "fetch_comments": "Rezensionen abrufen",
        "fetching": "Rezensionen werden abgerufen…",
        "fetch_complete": "✅ Abruf der Rezensionen abgeschlossen! ({count} Rezensionen abgerufen)",
        "excel_saved": "📂 Excel-Datei gespeichert!",
        "download_excel": "Excel-Datei herunterladen",
        "analyze_button": "Sentiment-Analyse & Word Cloud erstellen",
        "analyzing": "Analysiere…",
        "analysis_complete": "✅ Analyse abgeschlossen!",
        "sentiment_results": "Ergebnisse der Sentiment-Analyse:",
        "no_positive": "Keine positiven Rezensionen, Word Cloud konnte nicht erstellt werden.",
        "no_negative": "Keine negativen Rezensionen, Word Cloud konnte nicht erstellt werden.",
        "positive_wc": "Word Cloud der positiven Rezensionen",
        "negative_wc": "Word Cloud der negativen Rezensionen",
        "progress": "Fortschritt",
        "eta": "Geschätzte verbleibende Zeit"
    }
}